FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


COPY server-mcp.py .


ENV PORT=8080

EXPOSE 8080

# Variables env
ENV GITHUB_TOKEN_ENV=${GITHUB_TOKEN_ENV}

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

CMD ["python", "server-mcp.py"]
