FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir mlflow gunicorn

EXPOSE 8080

CMD mlflow server \
    --host 0.0.0.0 \
    --port 8080 \
    --backend-store-uri sqlite:///mlflow.db \
    --default-artifact-root ${ARTIFACT_ROOT} \
    --allowed-hosts "*" \
    --serve-artifacts
